package tcslab.syndesiapp.models;

/**
 * Contains broadcast types and extras constants.
 *
 * Created by Blaise on 06.05.2015.
 */
public enum BroadcastType {
    BCAST_TYPE_SERVER_STATUS,
    BCAST_TYPE_CONTROLLER_STATUS,
    BCAST_EXTRA_SERVER_RESPONSE,
    BCAST_TYPE_SENSOR_STATUS,
    BCAST_EXTRA_SENSOR_STATUS,
    BCAST_EXTRA_SENSOR_DATA,
    BCAST_TYPE_LOC_STATUS,
    BCAST_EXTRA_LOC_STATUS,
    BCAST_TYPE_LOC_POSITION,
    BCAST_EXTRA_LOC_OFFICE,
    BCAST_TYPE_AUT_STATUS,
    BCAST_EXTRA_AUT_DISP
}
